display_name: postgresql-status-monitor
package_name: postgresql-status-monitor

maintainer:
  name: Finzaiko
  email: finzaiko@gmail.com

priority: optional

section: x11

installed_size: 15700

dependencies:
  - libc6

essential: false

icon: assets/images/app_icon.png

postuninstall_scripts:
  - echo "App build..."

keywords:
  - Postgres
  - Monitor Status

generic_name: postgresql-status-monitor

categories:
  - Monitor
  - Dashboard

startup_notify: true